[package]
name = "code-maven"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3", features = ["derive"] }
liquid = "0.26.4"
regex = "1.9.3"
simple_logger = "4.2"
log = "0.4"
