navbar:
  start:
    - path: /
      title: Home
    - path: /tags/
      title: Tags
    - path: /slides/
      title: Slides
  end:
    - path: /archive
      title: Archive
    - path: /about
      title: About

