url: https://rust.code-maven.com
repo: https://github.com/szabgab/rust.code-maven.com
branch: main
navbar:
  start:
    - path: /
      title: Home
    - path: /tags/
      title: Tags
    - path: /slides/
      title: Slides
  end:
    - path: /archive
      title: Archive
    - path: /about
      title: About

