url: https://rust.code-maven.com
repo: https://github.com/szabgab/rust.code-maven.com
branch: main
tags:
  title: Tags
  description: Articles about Rust with tags
archive:
  title: Archive
  description: List of all the articles about the Rust programming language
navbar:
  start:
    - path: /
      title: Home
    - path: /tags/
      title: Tags
    - path: /slides/
      title: Slides
  end:
    - path: /archive
      title: Archive
    - path: /about
      title: About

