name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout repo of https://israel.szabgab.com/
      uses: actions/checkout@v3
      with:
        repository: 'szabgab/israel.szabgab.com'
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        path: israel.szabgab.com


    - name: Build debug version
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Build release version
      run: cargo build --release --verbose

    - name: Build demo site
      run: |
        cargo run --bin code-maven-web -- --root demo/ --outdir _site/

    - name: Rebuild the demo site
      run: |
        cargo run --bin code-maven-web -- --root demo/  --outdir _site/
        rm -rf _site/*
        cargo run --bin code-maven-web -- --root demo/  --outdir _site/

    - name: Generate demo site and compare to the stored version
      run: ./test.sh

    - name: Check cargo fmt
      run: cargo fmt --check

    - name: Clippy stop at any warning
      run: cargo clippy -- --deny warnings

    - name: Checkout repo of Rust Maven
      uses: actions/checkout@v3
      with:
        repository: 'szabgab/rust.code-maven.com'
        path: rust.code-maven.com

    - name: Build the Code-Maven site
      run: |
        rm -rf _site/*
        cargo run --bin code-maven-web -- --root rust.code-maven.com  --outdir _site/

    - name: Build the israel.szabgab.com site
      run: |
        rm -rf _site/*
        cargo run --bin code-maven-web -- --root israel.szabgab.com  --outdir _site/

